name: jyotishasha_app
description: "Jyotishasha Astrology App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0

  # ğŸŒ HTTP Requests (latest)
  http: ^1.2.2

  # ğŸ”¥ Firebase Core + Auth + Firestore
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.3

  # ğŸ”‘ Google & Facebook Sign-In
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1

  # ğŸ“ Google Places Autocomplete
  google_places_flutter: ^2.1.1

  # ğŸ—“ï¸ Date & Time Formatting
  intl: ^0.19.0

  # ğŸ’³ Razorpay Payments
  razorpay_flutter: ^1.3.7

  # ğŸ’ UI & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2

  # âš™ï¸ Environment Variables
  flutter_dotenv: ^5.1.0
  timezone: ^0.10.1

  syncfusion_flutter_pdfviewer: ^27.1.55
  share_plus: ^10.0.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  go_router: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/google.png
    - assets/icons/facebook.png
    - .env
