name: jyotishasha_app
description: "Jyotishasha Astrology App"
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^1.2.2
  firebase_messaging: ^15.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.3
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  intl: ^0.20.2
  razorpay_flutter: ^1.3.7
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  timezone: ^0.10.1
  provider: ^6.0.5
  geocoding: ^3.0.0
  syncfusion_flutter_pdfviewer: 31.2.15
  share_plus: ^10.0.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  go_router: ^16.3.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  audioplayers: ^6.5.1
  webview_flutter: ^4.10.0
  google_mobile_ads: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true    # ⭐ REQUIRED FOR L10N

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf

  assets:
    - assets/icons/google.png
    - assets/icons/facebook.png
    - .env
    - assets/images/
    - assets/audio/
    - assets/zodiac/
    - assets/data/reports.json
    - assets/data/reports_hi.json
    - assets/images/reports/

# ⭐ LOCALIZATION CONFIG (flutter ke bahar)
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart

